### ISSUE TITLE
jd误屏蔽

### ISSUE THREAD

**Issue by NIGHT-CORE** [vokins/yhosts#1]
union.click.jd.com

这个用来跳以及一些其他用途的

**Comment by vokins** [comment]
这个就是返利推广。

**Comment by vokins** [comment]
好吧。我觉得是要添加的。你们要是不想要的话，我把它放到专门的cps点击数据里面。

**Comment by NIGHT-CORE** [comment]
我觉着这类记录，可以注释掉，放顶部。
说明可能误屏蔽，需要的话自己开启。

**Comment by vokins** [comment]
为什么我当年一根筋的要加入这些数据呢？要是我自己也申请，放出来返利连接，说不定早也赚的盆满钵满。哈哈，数据今晚上更新，我要好好验证一下，顺便精简一下其他统计数据，只保留最核心的去广告数据好了。

**Comment by NIGHT-CORE** [comment]
好想法。
不同host之间没有重复吧，是独立的吧。

**Comment by vokins** [comment]
全部独立，可以自己组合
