### ISSUE TITLE
easyhosts 去广告规则 引用许可请求

### ISSUE THREAD

**Issue by forkgood** [vokins/yhosts#100]
项目：easyhosts
Github：https://github.com/forkgood/easyhosts
项目主页：https://windows.cat
由于程序自动更新，我的项目会使用到您更新的去广告项目规则，留意到使用您的项目需要得到许可，所以发此Issues征求同意。

期待您的回答，如果因任何些原因，无法允许其他项目进行整合，您做出决定后我们会及时取消使用，感谢！: D

**Comment by vokins** [comment]
禁止商业用途，保留所有数据内容。其他我没意见。

**Comment by forkgood** [comment]
感谢许可，以及规则更新工作，祝每天好运。

**Comment by vokins** [comment]
好的，辛苦了，谢谢！
