### ISSUE TITLE
Inappropriate sites at the top of hosts file

### ISSUE THREAD

**Issue by xunzhou** [vokins/yhosts#101]
There're bunch of inappropriate sites at the top of hosts file probably should be removed? 
`#uvwxyz.xyz
74.222.26.86 bbs.uvwxyz.xyz
74.222.26.86 ipv6.uvwxyz.xyz
74.222.26.86 uvwxyz.xyz
74.222.26.86 www.uvwxyz.xyz
74.222.26.90 bbs.uvwxyz.xyz
74.222.26.90 ipv6.uvwxyz.xyz
74.222.26.90 uvwxyz.xyz
74.222.26.90 www.uvwxyz.xyz
#gaysex
216.58.199.243 www.gaysex18.net
216.58.200.243 www.gaysex18.net
64.233.188.121 www.gaysex18.net
172.217.26.115 www.gaysex18.net
172.217.25.211 www.gaysex18.net
104.27.164.22 gaysex69.net
172.217.27.147 gaysexhd.net
104.27.164.22 www.gaysex69.net
216.58.200.243 www.sexgayhd.net
172.217.27.147 www.gaysexhd.net
`

**Comment by vokins** [comment]
能提供官方数据的ip我就把他加入到official分类下面，不能提供的官方ip的我就把他加入3rd分类下面。
具体你们双方有争论还是有歧视跟我都没关系。
对我来说，只是加入群内别人的反馈的数据而已。
不想看到的话可以用脚本获取的时候sed去除。
如果有捐赠的话请提供订单号流水号我来为你定制vip名单去除。
