### ISSUE TITLE
随时风暴英雄问题

### ISSUE THREAD

**Issue by panyuhang93** [vokins/yhosts#103]
系统:Android
运营商:电信
app名称:随身风暴英雄2.52
下载地址:http://heroes.blizzard.cn/minisite/appsite/
问题显示:
使用hosts前
![1](http://wx4.sinaimg.cn/large/d3685f0bgy1fh3qle29ffj20u01hcnpd.jpg)
使用hosts后
![2](http://wx1.sinaimg.cn/large/d3685f0bgy1fh3qlfyiycj20u01hc1kx.jpg)

**Comment by panyuhang93** [comment]
使用前
http://wx4.sinaimg.cn/large/d3685f0bgy1fh3qle29ffj20u01hcnpd.jpg
使用后
http://wx1.sinaimg.cn/large/d3685f0bgy1fh3qlfyiycj20u01hc1kx.jpg

不好意思

**Comment by vokins** [comment]
OK，已修复，感谢反馈。
