### ISSUE TITLE
你好，请删除click.simba.taobao.com

### ISSUE THREAD

**Issue by hackson99** [vokins/yhosts#107]
你好，请删除click.simba.taobao.com，否则我在淘宝主页搜索商品，点击商品的时候，提示打不开网页。谢谢咯。不然我每次同步你的hosts文件后，还要手动#127.0.0.1 click.simba.taobao.com  相当的麻烦。谢谢。

**Comment by vokins** [comment]
为什么要删除？这是广告

**Comment by passearth** [comment]
请问怎么删除？

2017-07-25 15:00 GMT+08:00 vokins <notifications@github.com>:

**Comment by Biercenter** [comment]
这个确实比较麻烦，经常遇到什么值得买跳转淘宝的时候无法打开。
