### ISSUE TITLE
误报

### ISSUE THREAD

**Issue by abc45628** [vokins/yhosts#108]
yun.duiba.com.cn会导致腾讯动漫安卓版的逗比商城白屏

**Comment by vokins** [comment]
动漫为什么需要商城？

**Comment by abc45628** [comment]
逗比是腾讯动漫的一个积分，可以换点券来看书，也可以换些小玩意

**Comment by abc45628** [comment]
b.bst.126.net
这个会导致网易博客的评论区头像不见了http://blog.163.com/seo_technology/blog/static/195684049201302592952295/

**Comment by vokins** [comment]
duiba.com.cnz自己加入白名单吧，
127.0.0.1 activity.m.duiba.com.cn
127.0.0.1 embedlog.duiba.com.cn
127.0.0.1 yun.duiba.com.cn
127.0.0.1 www.duiba.com.cn
最好全部都要加入白名单TAT
