### ISSUE TITLE
辛苦了，用过最好的hosts去广告源

### ISSUE THREAD

**Issue by cutefox123** [vokins/yhosts#111]
我可以在http://www.runningcheese.com/appshare
文章APP去广告一栏中推荐这个hosts源么？
酷安私信您没有回(≧▽≦)
确实是一份真的很用心的hosts

**Comment by vokins** [comment]
可以。ps您定制的火狐很好用。

**Comment by cutefox123** [comment]
啊呀呀呀呀呀 回复了(≧▽≦) 谢谢 你的hosts也好棒(^_^)
