### ISSUE TITLE
打开qq空间，公众空间的视频会一直后台自动播放无法控制，如果可以请直接屏蔽掉这类空间吧

### ISSUE THREAD

**Issue by hzcxdgioa** [vokins/yhosts#113]
https://user.qzone.qq.com/3094113831/main
用chrome打开qq空间，就会莫名有声源，但是找不到出处，移除hosts正常可控。

**Comment by vokins** [comment]
没看懂你想表达什么意思？
用了hosts可以正常播放？
不用hosts反而不能播放？

**Comment by hzcxdgioa** [comment]
应该是hosts屏蔽了某个js功能，导致部分特殊的视频，在加载的时候，会自动播放，而且自动播放的时候，是后台有声音，前台不知道是哪个在播放，同时也无法暂停视频播放。

下拉页面的时候，视频会自动开始加载，但是已经开始播放了，它还是在自动加载，不替换成播放窗口，导致不能控制该视频，
好像主要集中在非好友的视频上，也就是好友转发的视频，和好友热播视频，会出现这种状况

**Comment by vokins** [comment]
已修复，如果你那边测试过还有问题再反馈。
