### ISSUE TITLE
某广告平台域名

### ISSUE THREAD

**Issue by BROBIRD** [vokins/yhosts#115]
```
jiaeasy.net
jiayi1.oss-cn-shanghai.aliyuncs.com
```

**Comment by BROBIRD** [comment]
`godloveme.cn`

**Comment by vokins** [comment]
请尽可能多的提供信息。单纯提供域名不予以添加。谢谢合作。

**Comment by BROBIRD** [comment]
手机端访问www.zdfans.com即可发现“佳易”的广告
给你发issue之前我已经确认过了。
我参与维护的项目：https://github.com/ACL4SSR/ACL4SSR

2017年8月15日 21:52，"vokins" <notifications@github.com>写道：

**Comment by vokins** [comment]
在路由器部署了yhosts的情况下，测试了几个ua：小米浏览器，qq浏览器手机版，uc浏览器，均未发现广告。实机测试了oppo r11 plus也未发现广告。其提供源代码截图。并告知具体网络环境。

**Comment by BROBIRD** [comment]
刚才测试了一下发现似乎已经不再加载这个广告了。
加或者不加，您定夺一下吧。

**Comment by vokins** [comment]
无法重现暂不加入，感谢反馈

**Comment by BROBIRD** [comment]
广告图片是这个
![](http://jiayi1.oss-cn-shanghai.aliyuncs.com/640cheng200/640x200_2_red.png)

**Comment by vokins** [comment]
下次只提供图片地址就可以了。或者src=xxxx的部分网页源码也是可以的
