### ISSUE TITLE
可能会导致淘宝客服聊天及接入异常

### ISSUE THREAD

**Issue by Mosney** [vokins/yhosts#116]
用的是pdcn路由器方案 
具体表现为WiFi下淘宝客户端-我的小蜜-人工客服发送聊天信息失败 切换数据流量后恢复正常
另外ISP为中国移动 个人认为不是移动的锅

**Comment by barkim** [comment]
古哥论坛 http://www.gugeys.com/
这个直接上不了，看代码是直接把这个网站墙了，能修正吗

**Comment by vokins** [comment]
淘宝客服我也测试了没有任何问题。
www.gugeys.com已修复。
