### ISSUE TITLE
澳门赌场辣鸡广告域名提交，希望作者大大予以屏蔽

### ISSUE THREAD

**Issue by wangzongle** [vokins/yhosts#117]
www.aombjl099.com
www.sb88b.com
fc56b.me
www.76802.net
www.bb1429.com
www.xpjylc9977.com
3180555.com
wwww.551144.com
538i.me
www.1933000.com
www.878090.com
wwww.495495.com
wwww.649649.com
www.203710.com
www.kxmav2.com
www.jinshagt222.com
c16cp358.com

**Comment by vokins** [comment]
单纯的提供域名治标不治本，可以告知是在什么网站弹出的这些网址，我们会分析其网页代码，尽量从源头屏蔽此类网址

**Comment by wangzongle** [comment]
www.javbus.com
javlibrary.com
之类的上面的横幅广告

**Comment by vokins** [comment]
收到，回去处理

**Comment by vokins** [comment]
*/ads/*
使用abp或者urlfilter屏蔽这个即可。
