### ISSUE TITLE
请问这个域名加在hosts里是干嘛的？

### ISSUE THREAD

**Issue by imbear** [vokins/yhosts#13]
#uvwxyz.xyz
45.35.43.168 uvwxyz.xyz
45.35.43.168 www.uvwxyz.xyz
45.35.43.168 bbs.uvwxyz.xyz
45.35.43.170 ipv6.uvwxyz.xyz

**Comment by vokins** [comment]
看分类英文单词：智能转向

**Comment by imbear** [comment]
主要是不明白这个和广告屏蔽有什么关系，因为就这几个域名不一样处理
2016年6月15日 18:17，"vokins" <notifications@github.com>写道：

**Comment by vokins** [comment]
yhosts不止包含广告屏蔽功能，还有智能转向，软件验证信息屏蔽，互联网劫持屏蔽，cps劫持，病毒下载屏蔽等其他功能，如果你有一些网站无法访问，并提供该网站的官方提供的IP数据转向，并截图提交，我一样可以帮助添加。

**Comment by imbear** [comment]
哦，和google的hosts一样用途。原以为只是广告屏蔽用
2016年6月15日 下午6:50，"vokins" <notifications@github.com>写道：

**Comment by vokins** [comment]
不是,google的hosts只有智能转向数据

**Comment by imbear** [comment]
嗯好的，谢谢你的回答
2016年6月15日 21:49，"vokins" <notifications@github.com>写道：

**Comment by vokins** [comment]
不客气
