### ISSUE TITLE
請求屏蔽該網站的廣告

### ISSUE THREAD

**Issue by my32154** [vokins/yhosts#131]
希望屏蔽thzibt.com的廣告（主要是手機端用），可以有償

**Comment by vokins** [comment]
网站广告为：
http://173.208.177.227/6/605.gif

此类网站可以叠加我们的vip定制数据:
https://raw.githubusercontent.com/vokins/yhosts/master/vip/img.txt


urlfilter可以暂时屏蔽
http://173.208.177.227/*
http://thibt.com/source/plugin/yy_transv/js/cmp.js
或者使用我们的dnsmasq：
https://github.com/vokins/yhosts/blob/master/dnsmasq/ip.conf
广告ip已标记并更新
