### ISSUE TITLE
subhd.com字幕网站被屏蔽

### ISSUE THREAD

**Issue by Biercenter** [vokins/yhosts#134]
subhd.com字幕网站被屏蔽了，偶尔下载字幕都是在这个网站下载，今天打不开发现被hosts屏蔽了。

**Comment by vokins** [comment]
你好，您反馈的问题已经收到。这是由于阿起开发的强大自动广告分析处理系统对页面进行分析处理后得出的数据，我们将不断完善相关的白名单数据。将在稍后的版本中进行修复！感谢您的反馈！
