### ISSUE TITLE
yhosts 误杀 cdn.staticfile.org

### ISSUE THREAD

**Issue by neoFelhz** [vokins/yhosts#136]
[staticfile.org](https://staticfile.org) 是掘金提供、七牛赞助的前端开发公共 CDN 库服务。yhosts 误杀了 CDN 域名 `cdn.staticfile.org`

**Comment by vokins** [comment]
此域名位于virus.txt文件内，属于之前添加的已知的病毒网站调用的域名。
请提供正常的知名网站调用此域名的代码实例。
否则不予解除。

**Comment by neoFelhz** [comment]
@vokins 
https://github.com/search?l=&q=cdn.staticfile.org&ref=advsearch&type=Code&utf8=%E2%9C%93
仅仅在 GitHub 上搜索该 CDN 域名会得到 97000 余个结果。
您能否确认这 97000 余的调用全部来自病毒网站？
如果 yhosts 将 掘金 和 七牛 提供的 前端公共 CDN 库 **不负责任地没有研究每一个域名的用户**，而仅仅因为病毒网站的调用就将其加入 hosts 屏蔽列表，这令我感到遗憾。

**Comment by neoFelhz** [comment]
除此以外，所有 SSPanel 的 jquery 均使用 `cdn.staticfile.org` 加载。

**Comment by vokins** [comment]
那你提供使用此域名的正规网站。

**Comment by neoFelhz** [comment]
查阅了你们的 #124 ，我相信你们不太可能移除一个广泛使用的 CDN 公共库的域名，仅仅因为一个病毒网站的调用而没有调查这个域名的真实用途、哪怕可能导致很多网站因此不能正常使用。
我对你们小组的工作态度、你们在 #134 中提到的 广告分析系统 的能力感到失望。
你们不配作为你们在 README 中提到的 `最好的 hosts`。
我会关闭这个 issue，让你和你们的 VIP 用户高潮去吧。

**Comment by vokins** [comment]
爱用不要。

**Comment by neoFelhz** [comment]
![photo_2017-10-22_15-34-33](https://user-images.githubusercontent.com/19367350/31859405-5bebd0cc-b73e-11e7-9a77-79baa13cf796.jpg)
顺便说一句，这条 issue 的动态目前正在 Telegram 上直播，希望项目维护者注意自己的言辞。

**Comment by vokins** [comment]
爱用不用。
