### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by zxhdmx** [vokins/yhosts#138]
oppo-browser 那一栏能去掉吗？平时也会用浏览器看看新闻

127.0.0.1 disp.titan.mgtv.com
127.0.0.1 disp1.titan.mgtv.com
这些不是广告吧

土豆、网易云音乐的广告能添加上去吗？

**Comment by vokins** [comment]
不是广告是什么内容具体说一下.

**Comment by zxhdmx** [comment]
@vokins 应该是视频资源的链接吧

**Comment by vokins** [comment]
嗯,那个暂时去掉了.土豆和网易云音乐还有广告?请给链接

**Comment by zxhdmx** [comment]
@vokins 土豆下载链接：http://umcdn.uc.cn/down3/cc8a86d9ccd48187/newtd_V6.13.2.1108.0001_cc8a86d9ccd48187.apk 视频广告

网易云音乐下载：http://d1.music.126.net/dmusic/CloudMusic_official_4.2.2.971141.apk 
 开屏广告 http://img04.sogoucdn.com/app/a/100520146/34b2cf01e4e9dc9723818e4ff0bcaff8
还有这种广告应该去不掉吧？http://img04.sogoucdn.com/app/a/100520146/d6af466ecb29f9b3a246e6c63da72a4d

**Comment by vokins** [comment]
非单独的广告域名无法使用hosts方式屏蔽.可以使用项目里的原创收集的urlfilter或者文件夹屏蔽替换方式,比如hosts.zip刷机包

**Comment by zxhdmx** [comment]
@vokins 原来如此 好吧。

1.优酷客户端的广告还在，用网页看视频会显示“请允许cookie储存”看不了视频。

2.您试试打开搜狐视频的网页看看。应该是屏蔽了不相关的东西

3. 打不开电脑版的搜狐视频网址tv.sohu.com 

4.www.luomi.com 洛米广告

**Comment by zxhdmx** [comment]
@vokins 原来如此 好吧。

1.优酷客户端的视频广告还在。用网页看视频会显示“请允许cookie储存”看不了视频。

2.您试试打开搜狐视频的网页看看。应该是屏蔽了不相关的东西
1. 打不开电脑版的搜狐视频网址tv.sohu.com

4.www.luomi.com 洛米广告

**Comment by zxhdmx** [comment]
@vokins 原来如此 好吧。

1.优酷客户端的视频广告还在。用网页看视频会显示“请允许cookie储存”看不了视频。

2.您试试打开搜狐视频的网页看看。界面有问题，应该是屏蔽了不相关的东西

3. 打不开电脑版的搜狐视频网址tv.sohu.com

4.www.luomi.com 洛米广告

**Comment by vokins** [comment]
1.用群内的旧版优酷app即可.
2.电脑用hosts.txt不要用hosts
3.未发现问题
4.不接受直接提交数据,请提供出现广告的页面网址.网络劫持的情保存网页传到云盘我们分析.谢谢

**Comment by zxhdmx** [comment]
@vokins 那就直接发应用吧。
人人影视http://61.158.163.23:8080/v2.4.2_renren_242_jiagu_sign_new.apk
广告：启动页，影视详情，我的 

village（山寨云） https://www.coolapk.com/apk/com.downloading.main.baiduyundownload 
广告：启动页 可能还有别的

**Comment by vokins** [comment]
山寨云我们在群里以前测试过,没发现有广告.而且代码中出现的几处域名军存在于hosts之中
127.0.0.1 adash.man.aliyuncs.com
127.0.0.1 alog.umeng.com
127.0.0.1 alog.umengcloud.com
127.0.0.1 m-adash.m.taobao.com
127.0.0.1 mqqad.html5.qq.com
127.0.0.1 test2014.adview.cn
rrys已更新

**Comment by zxhdmx** [comment]
@vokins rrys应该还有这几条

127.0.0.1 renren2.maoyun.tv
127.0.0.1 app.xysryh.com
