### ISSUE TITLE
芒果TV 的视频广告失效了

### ISSUE THREAD

**Issue by zxhdmx** [vokins/yhosts#145]
如题

**Comment by vokins** [comment]
暂时无法重现。
环境：1.极米z4x，芒果tv客户端（vip账号已退出）。山东联通；
2.蓝蝶模拟，芒果tv客户端，山东长城宽带。均无法重现。
建议排查自己的运营商是否有网络劫持，或者使用fillder检测看看网络请求。并且吧内容以txt形式发上来。谢谢配合。

**Comment by vokins** [comment]
https://telerik-fiddler.s3.amazonaws.com/fiddler/FiddlerSetup.exe

**Comment by vokins** [comment]
https://www.baidu.com/s?ie=utf-8&f=3&rsv_bp=1&tn=baidu&wd=fiddler%20%E6%89%8B%E6%9C%BA%E6%8A%93%E5%8C%85&oq=fiddler&rsv_pq=e54228bc0000f026&rsv_t=57f4TbJ0sPijoMDyo5s0ZpniHox49EX85Nve3Q8IjrvSmMgqNF%2BZzX%2BDpiM&rqlang=cn&rsv_enter=1&rsv_sug3=1&rsv_sug1=1&rsv_sug7=100&rsv_sug2=1&prefixsug=fiddler&rsp=0&rsv_sug4=2100

**Comment by zxhdmx** [comment]
@vokins 芒果TV5.6.2（最新）版本 点击节目比如变形计会一直卡在加载视频

**Comment by vokins** [comment]
家里是什么地区的什么宽带？更换其他运营商可否重现，请确认是否为网络劫持。我这里依旧无法重现。
