### ISSUE TITLE
有没有不包含个人情感的纯洁版本

### ISSUE THREAD

**Issue by coderstory** [vokins/yhosts#149]
就是不屏蔽一号店啊魅族啊什么的网站的hosts

**Comment by vokins** [comment]
没有。但是可以自己组合啊。moot文件夹下的谨慎选择就可以了。个人喜好，他们不无故取消我得订单和魅族售后死不承认我在他们官方商场的订单。什么时候给我赔礼道歉，什么时候删除掉。
