### ISSUE TITLE
s.img.mix.sina.com.cn会把sina的slide图片阻断了，希望能够去掉

### ISSUE THREAD

**Issue by david-holonet** [vokins/yhosts#15]
请看如下链接：
http://slide.news.sina.com.cn/s/slide_1_2841_98125.html?cre=photopagepc&mod=picg&loc=1&r=9&doct=0&rfunc=37#p=1
![screen shot 2016-06-20 at 16 34 01](https://cloud.githubusercontent.com/assets/15024294/16187820/fa86e976-3704-11e6-9594-8a2cd0a0a325.png)

desktop, chrome browser, Mac OS X.

**Comment by vokins** [comment]
ok
