### ISSUE TITLE
[误杀]TIM文件无法下载

### ISSUE THREAD

**Issue by BeLittleYang** [vokins/yhosts#150]
反馈域名：oth.str.mdt.qq.com
重现步骤：在聊天文件中下载出错（保持在0Kb），上传情况相同，添加白名单后可用（QQ未经测试）

**Comment by BeLittleYang** [comment]
反馈域名：oth.eve.mdt.qq.com
重现步骤：Android端进入群文件无法加载（QQ未经测试）

**Comment by vokins** [comment]
已测试米6，hosts，tim登录后，群文件下载正常。

**Comment by BeLittleYang** [comment]
暂时关闭issue，后续观察
