### ISSUE TITLE
是否需要加入这个Host

### ISSUE THREAD

**Issue by ookangzheng** [vokins/yhosts#151]
https://www.zhihu.com/question/46746200/answer/189862510
<img width="715" alt="screen shot 2018-02-20 at 4 58 44 pm" src="https://user-images.githubusercontent.com/6301735/36415039-6a35f1e6-165f-11e8-8965-0e2306fab9d4.png">

**Comment by vokins** [comment]
他们公司的127.0.0.1 wm.makeding.com开头的下载域名几年前就入了。正常的话是不会下载到任何个他们公司的**推广**app的。
目前，yhosts不接受任何收集式的其他hosts内容。
原因有几个：
1.大部分数据仍在四处不更新的传播我们之前的旧数据，导致了一些误杀。
2.yhosts重写之初就着重效果表现，而非数据量庞大上。
3.我屏蔽魅族，一号店，海信等，是因为后买过他们的产品，并遭受了不公正不友好的售后待遇。这些数据带有个人色彩，并存放在moot文件夹下，如果其他人不喜欢，可以合并所有非moot文件夹下的数据。这一点，我不接受关于请求撤销他们数据的任何意见，除非他们亲自承认错误并当面道歉。


如果有广告问题，请具体提交复现方式，我们会处理。
yhosts可以配合ylists（ABP）规则使用。
