### ISSUE TITLE
Hosts 数据出错

### ISSUE THREAD

**Issue by xlighting2017** [vokins/yhosts#158]
Hosts 里面应该只有域名吧， 昨天的更新出现了这样一条

`127.0.0.1 http://www.cqsta.com/cc/sh.js`

转换成 dnsmasq配置文件后，会直接导致 dnsmasq 出现  segfault
![image](https://user-images.githubusercontent.com/25970065/41332095-f184d934-6f0e-11e8-9a7c-5af0b46acf68.png)

**Comment by vokins** [comment]
fix and thanks
