### ISSUE TITLE
autohome汽车之家过多过滤，希望重新整理一下，多谢

### ISSUE THREAD

**Issue by david-holonet** [vokins/yhosts#16]
http://www.autohome.com.cn/beijing/把好些正常的图片都过滤了，我删掉了如下域名后显示正常，但广告也有出现，不过还好不太会影响：
c.autohome.com.cn
33.autohome.com.cn
adm3.autoimg.cn
adm2.autoimg.cn
adm1.autoimg.cn
adm0.autoimg.cn
特别是c.autohome.com.cn，加上后很多链接都失效了。

**Comment by vokins** [comment]
[](url)

看源代码您说的这些官方都认定都是广告.
不做修正,谢谢反馈
