### ISSUE TITLE
Sobooks的广告反馈

### ISSUE THREAD

**Issue by Chandler-Lu** [vokins/yhosts#169]
网址：https://sobooks.cc/xiaoshuowenxue
平台：桌面端
广告位置：
![wx20181109-104857](https://user-images.githubusercontent.com/18322610/48240243-2322ef80-e40d-11e8-9e30-2004f1663ae9.png)
广告域名：
```
127.0.0.1	xvyljkr.com
127.0.0.1	alifixed.cn
127.0.0.1	alistatic.cn（已有）
```
V大好久不见了2333

**Comment by vokins** [comment]
感谢反馈已更新
