### ISSUE TITLE
sina首页增加两个广告域名过滤，多谢

### ISSUE THREAD

**Issue by david-holonet** [vokins/yhosts#17]
creative.1111cpc.com
ad.1111cpc.com

**Comment by vokins** [comment]
127.0.0.1 ad.1111cpc.com
127.0.0.1 creative.1111cpc.com
请问这个域名在哪里找到的?请给出源代码瘠土或者具体页面,谢谢!

**Comment by CloudnuY** [comment]
![_2016-07-01_ 2_54_51](https://cloud.githubusercontent.com/assets/14636247/16676077/66b6cac4-44f9-11e6-8be2-51b50e48f5ab.jpg)
搜1111cpc搜到这儿了，这是我被联通劫持插入广告的截图⬆️。。。。。。。

**Comment by vokins** [comment]
ok,数据已更新
