### ISSUE TITLE
若能屏蔽以下几个赌博网站域名，应该不错

### ISSUE THREAD

**Issue by Xuxianxiang** [vokins/yhosts#171]
以下域名均为赌博网站（新神乐网和其他赌博网站）之域名（所谓幸运28游戏）
JC也抓过干类似东西的人了
周围有人被坑过，希望能帮到更多的人
```
127.0.0.1 m.xsl280.com
127.0.0.1 www.xsl280.com
127.0.0.1 www.xsl281.com
127.0.0.1 zj.xsl280.com
127.0.0.1 www.7ldou.com
127.0.0.1 www.tangchao28.com
127.0.0.1 www.douyu28.com
```

**Comment by vokins** [comment]
127.0.0.1 www.xsl280.com
127.0.0.1 www.xsl281.com
127.0.0.1 www.7ldou.com
只有这三个可以访问，已加入。

**Comment by vokins** [comment]
有问题请再次留言。谢谢反馈！

**Comment by Xuxianxiang** [comment]
127.0.0.1 xmrminer.cc
127.0.0.1 coinhive.com
127.0.0.1 www.coinhive.com
加入这几个条目，以防止被JS脚本挖矿所利用如何？
