### ISSUE TITLE
广告 JS 域名反馈

### ISSUE THREAD

**Issue by Metaphilium** [vokins/yhosts#176]
我这在浏览某些网页时能看到推广，查看源码后 JS 来自于 [y.pzclw.cn](y.pzclw.cn)，单独打开这个域名会跳转到 [wangmeng.baidu.com](wangmeng.baidu.com)（已被屏蔽）打不开，但来自 [y.pzclw.cn](y.pzclw.cn) 的 JS 是可以被正常加载的，而 [pzclw.cn](pzclw.cn) 会跳转到一个叫「评职称论文网」的看起来正常的网站。

**Comment by vokins** [comment]
暂时添加了这个子域名，最好能把出现广告的页面url，网址提供一下，方便分析，谢谢！

**Comment by Metaphilium** [comment]
> 暂时添加了这个子域名，最好能把出现广告的页面url，网址提供一下，方便分析，谢谢！

**Comment by Metaphilium** [comment]
> 暂时添加了这个子域名，最好能把出现广告的页面url，网址提供一下，方便分析，谢谢！

[http://mobile.lyd.com.cn/news/system/2019/02/08/030990867.shtml](url)
上方是出现广告的页面，另外前几天又发现了一个 [rabc1.iteye.com](url) 也是相同的模式，但是我忘了出现在哪里了，不好意思。

**Comment by vokins** [comment]
http://y.pzclw.cn/lfjnxv.js http://t.pzclw.cn/pp/4=qjbuk80ocy,c0xf5wmbvk&d9=8w?hzko1=sdphsh_5tqag_cd0http://t.pzclw.cn/m.html?mediaid=5ad2c410af79838bff4aa09e51cdbba9e14150cedf90a2ce87a70a57f02382b878db2aa7a3ef2b0ce02f1128301b64a6&cookie_version=2&timestamp=1549685301&ext_data=

**Comment by vokins** [comment]
数据已更新，测试一下，有问题再反馈，谢谢

**Comment by Metaphilium** [comment]
经测试没有问题，谢谢。

**Comment by vokins** [comment]
好的，有问题再联系。
