### ISSUE TITLE
请求用于嵌入式设备的大面积部署

### ISSUE THREAD

**Issue by JackMerlin** [vokins/yhosts#178]
尊敬的开发者 vokins 您好，我是一名独立自由开发者，我正在进行一个基于路由器的过滤广告自定义脚本计划，该计划想使用您的 hosts 文件作为过滤广告的规则之一。
我注意到您的许可证是私有的，因此我想得到您的明确同意后再进行该项目的开发，以下是我的使用目的：

0. 这不是一个商业活动，我将其定义为非营利性质不做任何担保的广告过滤脚本。
1. 使用您的广告过滤规则在Asuswrt、Asuswrt-Merlin 及其衍生固件的路由器上进行广告过滤。
2. 我的过滤广告项目计划采用 GPLv3 或 MPLv2 许可证，因此不知嵌入您的广告过滤规则是否会引起许可歧义。
3. 过滤广告项目开发者短期没有计划以此盈利（但保留日后因维护过于庞大转型收入捐款的收益方式），但是不保证用户安装脚本后用于网吧、酒店等营利的场所。
4. 可能会根据需求再编辑您的广告过滤规则，例如将 hosts 转换为更高效的 dnsmasq。
5. 可能会删减或增加一些内容，删减包括引起用户无法正常上网的功能，规则中的非 0.0.0.0、127.0.0.1 的真实解析，和其他过滤规则重复的内容。增加一些注释，例如声明来源和感谢等。
6. 为了实现以上的一些需求，您的过滤规则可能会被编辑后再上传到另外的 github 项目（或私人服务器），以另外一个项目地址（或私人服务器）作为更新源，但是始终会在清晰的位置指向您的 github 源地址，并可根据您的需求显示向您捐助等信息。

嗯，大致就是这些。

**Comment by vokins** [comment]
随便用吧，但是如果遇到数据有问题希望能首先把错误提交给我们。

**Comment by vokins** [comment]
目前有部分dnsmasq，但是不是全部，可以参考。

**Comment by JackMerlin** [comment]
感谢您的回复。
我会在收到有用户报告“误杀”等错误时与您第一时间共享此讯息。
此外，之所以未打算采用您的 dnsmasq 也是注意到可能包含的内容不如 hosts 文件全面。

最后，非常感谢您的授权，我会在项目启动后与您分享动态。

**Comment by vokins** [comment]
好的，祝好。

**Comment by JackMerlin** [comment]
> 
> 
> 好的，祝好。

目前项目开发受阻，项目前途未知，因其性质可能会和一些广告方纠纷，已有类似基于路由器的产品被要求下架。

现在的问题不在于开发和过滤规则，而是发布平台，相关社区均已屏蔽此类话题，没有平台可以承载项目的发布，以及未知的法律风险导致项目进度受阻，现在暂时不敢轻举妄动，并很有可能随时终止其项目。

希望我还会继续更新动态，谢谢您！
