### ISSUE TITLE
误杀

### ISSUE THREAD

**Issue by ziyuedi** [vokins/yhosts#179]
mipcdn.com误杀，导致百度移动端搜索结果使用mip的网站无法打开

**Comment by vokins** [comment]
请贴上具体网址，详细说明，谢谢

**Comment by ziyuedi** [comment]
> 请贴上具体网址，详细说明，谢谢

例如移动端百度搜索"mipcdn"，链接为https://m.baidu.com/s?word=mipcdn
![IMG_20190331_144324](https://user-images.githubusercontent.com/24859058/55285703-7816d080-53c3-11e9-845c-1fdad23d4758.png)
第二个结果链接为https://m.baidu.com/from=0/bd_page_type=1/ssid=0/uid=0/pu=usm%401%2Csz%40320_1004%2Cta%40iphone_2_6.0__/baiduid=998D98AB457F4812926AF35D298AD3EA/w=0_10_/t=iphone/l=1/tc?ref=www_iphone&lid=4537878292624695418&order=2&fm=alop&cyc=1&isAtom=1&is_baidu=0&h5ad=0&dict=-1&tj=www_normal_2_0_10_l3&wd=&eqid=3ef9c843b1d9e000100000035ca060c4&w_qd=IlPT2AEptyoA_yisJV3eHyq&tcplug=1&sec=37470&di=025ed6b85fba4c43&bdenc=1&tch=124.22.316.315.1.0&nsrc=IlPT2AEptyoA_yixCFOxCGZb8c3JV3T5ABfPNy6R2iv5nk_qva02HN6qJ7HNMzrIBVKwdoSYeM-PdzryOTVs6s1Yg0dmpTdukimgeKGlwwjPUsAEr2UqNNbWVS7
点击后跳转到https://m.baidu.com/mip/c/s/zhangzifan.com/baidu-mip-and-cdn.html
然后就会报错“无法建立与 zhangzifan-com.mipcdn.com 服务器的连接。”
![IMG_20190331_144711](https://user-images.githubusercontent.com/24859058/55285735-ea87b080-53c3-11e9-8741-52f5acb65aa5.png)
经检测是由于使用了这个项目的hosts导致
这个项目的hosts将mipcdn.com指向了0.0.0.0

**Comment by vokins** [comment]
hosts中并没有mipcdn这个域名，删除了几个相关的百度域名测试，你看看现在可以了吗？我试了下安卓机可以了

**Comment by ziyuedi** [comment]
https://github.com/vokins/yhosts/blob/master/dnsmasq/union.conf
第1436行`address=/.mipcdn.com/0.0.0.0`

**Comment by vokins** [comment]
好的，感谢
