### ISSUE TITLE
乐视app

### ISSUE THREAD

**Issue by ghost** [vokins/yhosts#18]
乐视安卓app  版本6.6.1有视频广告
湖北电信
可以参考以下规则更新
http://sub.adtchrome.com/adt-chinalist-easylist.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://easylist-downloads.adblockplus.org/easylistchina.txt
https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

**Comment by Hongnanjing** [comment]
湖北电信

**Comment by Hongnanjing** [comment]
可以参考以下规则更新
http://sub.adtchrome.com/adt-chinalist-easylist.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://easylist-downloads.adblockplus.org/easylistchina.txt
https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

**Comment by vokins** [comment]
使用的测试平台:5k路由器,在路由器端加载hosts,ipad和安卓均无广告.
请问是否使用的是这个数据源:https://raw.githubusercontent.com/vokins/yhosts/master/hosts

安卓系统更新完hosts后请注意改对权限，相关软件需要清除数据或者清理缓存并清理掉后台再重新打开APP，部分机器需要开关一次飞行模式或者重启手机。

**Comment by Hongnanjing** [comment]
有时候有有时候没有，不过还是谢谢
