### ISSUE TITLE
作者你好，我可以获得将此项目引用非盈利的开源项目吗？

### ISSUE THREAD

**Issue by user1121114685** [vokins/yhosts#181]
https://github.com/user1121114685/koolproxyR

这是我写的一个免费的开源项目，希望能引用大佬部分hosts.并获修改成专用格式。我会在项目上注明您的共享。

 盼复函

**Comment by modasi** [comment]
欢迎

At 2019-05-15 20:13:45, "联盟少侠" <notifications@github.com> wrote:


https://github.com/user1121114685/koolproxyR

这是我写的一个免费的开源项目，希望能引用大佬部分hosts.并获修改成专用格式。我会在项目上注明您的共享。

盼复函

**Comment by vokins** [comment]
可以，有一个要求是遇到问题请优先反馈给我们，谢谢，祝夏安。

**Comment by user1121114685** [comment]
感谢你们的辛苦付出

**Comment by JackMerlin** [comment]
我也在进行一个类似项目，但是现在因为 KP 下架一事有点担心，也许我们可以抱团取暖。
https://github.com/vokins/yhosts/issues/178

**Comment by vokins** [comment]
moot文件夹下数据比较有争议，可以默认不使用。

**Comment by user1121114685** [comment]
> moot文件夹下数据比较有争议，可以默认不使用。

感谢提醒。我以发布测试版本。才用的主hosts.txt与tvbox.txt大家反馈很好，如果将来有问题反馈一定第一时间提交到项目。感谢。

> koolproxyR 开发者您好，我也在进行一个基于 Asuswrt 及衍生固件的全 Shell 实现的广告过滤项目，已经于早前得到了该 hosts 项目作者同意用于我的项目 #178
> 
> 我想我们在做的事情是同样的工作，希望我们可以一起工作，共同搭建一个更好的广告过滤项目。
> 
> 我略会一些 Shell 脚本，并发布过一个在路由器上的[小项目](https://github.com/JackMerlin/USBAccelerator)，希望我们可以合作，一起进行广告拦截！
> 
> 谢谢！

[在tg上找到我](https://t.me/uVdZRF4D7IfcWDZAaXYA) 很高兴对大家有帮助，你可以通过这个链接找到我。欢迎大家相互交流。

**Comment by JackMerlin** [comment]
> [在tg上找到我](https://t.me/uVdZRF4D7IfcWDZAaXYA) 很高兴对大家有帮助，你可以通过这个链接找到我。欢迎大家相互交流。

不知您是否有可用于联系的电子邮箱？

**Comment by user1121114685** [comment]
1121114685@qq.com
