### ISSUE TITLE
Blocking cloud.rovio.com breaks Angry Birds Blast 'events' buttons

### ISSUE THREAD

**Issue by lightswitch05** [vokins/yhosts#182]
Hello,

I'm just writing to let you know that blocking `cloud.rovio.com` breaks the `events` button in the Angry Birds Blast app on iPhone. It is fine if you want to close this ticket and continue blocking that domain, I just wanted to report it so that you are aware that it is broken. 👍 thank you for maintaining this list

**Comment by vokins** [comment]
Repaired, thanks for feedback

**Comment by lightswitch05** [comment]
thanks!
