### ISSUE TITLE
为什么还再更新？

### ISSUE THREAD

**Issue by xiangfeigao** [vokins/yhosts#183]
希望继续更新，如果时间有限，希望能加入屏蔽教程，能让更多网友帮助你进行更新

**Comment by AnyWAT** [comment]
#version=201906182153
#url=https://github.com/vokins/yhosts

**Comment by vokins** [comment]
https://v.youku.com/v_show/id_XMTUyNTc2MDEwOA==.html

**Comment by user1121114685** [comment]
你好p2p.huya.com 对虎牙流畅度有影响，可以考虑放行（放行之后上传占满，不放行则不流畅直接卡）

----来自kooolproxyR 项目用户反馈

**Comment by user1121114685** [comment]
click.simba.taobao.com 对淘宝页面标记有广告字样连接的商品有影响，会导致无法打开。可以考虑放行，毕竟上淘宝就是为了买东西。

---- 来自kooolproxyR 项目用户反馈

**Comment by vokins** [comment]
> click.simba.taobao.com 对淘宝页面标记有广告字样连接的商品有影响，会导致无法打开。可以考虑放行，毕竟上淘宝就是为了买东西。
> 
> ---- 来自kooolproxyR 项目用户反馈

1.淘宝都认定且明确标注这个是广告。
2.屏蔽他并不影响自己返利购买（通过一淘）
暂时取消放入了cps里面。hosts.txt是全部数据包含moot（cps）.hosts是默认数据未包含moot数据。
所以，这两条数据都删除了

**Comment by user1121114685** [comment]
感谢
