### ISSUE TITLE
Domain name: fiddler2.com

### ISSUE THREAD

**Issue by DRSDavidSoft** [vokins/yhosts#186]
Hello sir,

I believe that the domain name `fiddler2.com` is a false positive as it's used by a legitimate product named [Telerik Fiddler](https://www.telerik.com/fiddler), which is used as a debugging proxy tool.

As it appears, the whole domain **fiddler2.com** should not be blocked as it not used for license verification, displaying ads or tracking users. The only type of tracking that I can think of is the first time installations, which can be also tracked from their other domains.

May I ask please to whitelist the `fiddler2.com` domain name?

Thank you.

**Comment by vokins** [comment]
fixerd , thank u
