### ISSUE TITLE
百度网盟跳转

### ISSUE THREAD

**Issue by abc45628** [vokins/yhosts#189]
fpb.sohu.com

**Comment by abc45628** [comment]
assp.sohu.com
qpb.sohu.com
这两个貌似是用来跳转的
测试连接http://m.sohu.com/a/242067134_100029920

**Comment by vokins** [comment]
感谢分享，这三条数据：
127.0.0.1 assp.sohu.com
127.0.0.1 fpb.sohu.com
127.0.0.1 qpb.sohu.com
已加入，谢谢
