### ISSUE TITLE
爱奇异广告过滤不了

### ISSUE THREAD

**Issue by ys1122** [vokins/yhosts#19]
爱奇异 ios的app无法过滤
爱奇异网页上无法播放

**Comment by lishengqiang** [comment]
网页版去掉  t7z.cupid.iqiyi.com 就可以播放了

**Comment by vokins** [comment]
请看使用说明

**Comment by mzryry** [comment]
请求删除 meta.video.qiyi.com 这个域名是网页版爱奇艺快进功能
添加域名 z8.cnzz.com

**Comment by mcapp** [comment]
爱奇艺误杀严重，安卓客户端无法搜索，vip充值界面打不开，反馈的常见问题不显示

**Comment by vokins** [comment]
@mcapp 已修复

**Comment by vokins** [comment]
@beyondroot 已修复
