### ISSUE TITLE
补充更新视频网站广告过滤地址

### ISSUE THREAD

**Issue by clion007** [vokins/yhosts#191]
active.admore.com.cn
g.163.com
mtty-cdn.mtty.com
static-alias-1.360buyimg.com
image.yzmg.com
files.jb51.net/image
common.jb51.net/images
du.ebioweb.com/ebiotrade/web_images
www.37cs.com
pic.iidvd.com
cnzz.com
statis.api.3g.youku.com
ad.m.qunar.com
aiseet.atianqi.com
.qiyipic.com
imgcache.qq.com
.ciimg.com
.51cto.com
msg.video.iqiyi.com
titan.mgtv.com
res.mgtv.com
wx2.sinaimg.cn
t7z.cupid.iqiyi.com
a.xiguaimg.com
k.youku.com
vali.cp31.ott.cibntv.net
vmindhls.tc.qq.com
ad.molitv.cn
sv-video.play.ott.video.qq.com
valipl.cp31.ott.cibntv.net
vali.cp31.ott.cibntv.net
yktd.m.cn.miaozhen.com
val.atm.youku.com
ems.youku.com
ipm.atm.youku.com
g3.ykimg.com
ykugc.cp31.ott.cibntv.net
lives.l.qq.com/livemsg
valipl-dns.cp31.ott.cibntv.net
splashqqlive.gtimg.com
vv.video.qq.com

**Comment by vokins** [comment]
首先，hosts文件并不支持通配符：
.51cto.com
.ciimg.com
.qiyipic.com
其次，hosts无法提供如下或者像urlfilter，abp类似的精准过滤，类似的数据放在hosts文件里面，会把整个域名都ban掉，出现其他问题。
common.jb51.net/images
files.jb51.net/image
lives.l.qq.com/livemsg
du.ebioweb.com/ebiotrade/web_images
第三，在您提供的数据里面，有一行重复：
vali.cp31.ott.cibntv.net
我们的数据里面本身已经包含以下部分：
ad.molitv.cn
ipm.atm.youku.com
val.atm.youku.com
www.37cs.com
yktd.m.cn.miaozhen.com
vmindhls.tc.qq.com
t7z.cupid.iqiyi.com
第四，有些域名本身包含广告，但是无法屏蔽或者屏蔽后会导致一些问题，比如：
g.163.com，会导致新闻客户端一些功能无法正常使用。
res.mgtv.com，看起来这个是芒果TV的资源域名，屏蔽后可能会导致一些非广告图片无法正常显示
目前芒果用了我们的数据应该没有广告了吧。如果有请提供app版本，平台等信息，我们会在复查。
其他域名会酌情加入合并到主数据，谢谢反馈。

**Comment by vokins** [comment]
127.0.0.1 a.xiguaimg.com
127.0.0.1 active.admore.com.cn
127.0.0.1 ad.m.qunar.com
127.0.0.1 aiseet.atianqi.com
127.0.0.1 cnzz.com
127.0.0.1 ems.youku.com
127.0.0.1 g3.ykimg.com
127.0.0.1 image.yzmg.com
127.0.0.1 imgcache.qq.com
127.0.0.1 k.youku.com
127.0.0.1 msg.video.iqiyi.com
127.0.0.1 mtty-cdn.mtty.com
127.0.0.1 pic.iidvd.com
127.0.0.1 splashqqlive.gtimg.com
127.0.0.1 static-alias-1.360buyimg.com
127.0.0.1 statis.api.3g.youku.com
127.0.0.1 sv-video.play.ott.video.qq.com
127.0.0.1 titan.mgtv.com
127.0.0.1 vali.cp31.ott.cibntv.net
127.0.0.1 valipl-dns.cp31.ott.cibntv.net
127.0.0.1 valipl.cp31.ott.cibntv.net
127.0.0.1 vv.video.qq.com
127.0.0.1 wx2.sinaimg.cn
127.0.0.1 ykugc.cp31.ott.cibntv.net

**Comment by clion007** [comment]
哦，对了，忘了说，我是路由器自动把这个规则生成dnsmasq规则数据的，不是纯host数据
谢谢详细的补充说明，我会把已经包含的，及可能出现非正常过滤的删除掉。
