### ISSUE TITLE
请求添加 hzxdvs.cn

### ISSUE THREAD

**Issue by metaphilium** [vokins/yhosts#194]
最近一段时间一打开简书等的页面就被劫持到这个域名下的浏览器推广页面，可能是本地运营商劫持所致。

**Comment by vokins** [comment]
搜索了一下，发现如下内容
https://js.hbssjd.cn/m301650.js
https://ws2.hbssjd.cn/ms/a.js?b=200473!301650!88!640!150!200&u=5!4.1.1!3!1!bWky!16!0!1&c=1!0!x!2!16!2!24!2048!1152!0!5!0!x!1!d2luMzI%3D!0!0!0!0!0!1!3!x!d3d3LmppYW5zaHUuY29t!1!1!1!R29vZ2xlSW5jLn5BTkdMRShSYWRlb25SWDU4MFNlcmllc0RpcmVjdDNEMTF2c181XzBwc181XzAp!14!0!0!0!65!63!-1!-1!2796853476&f=64872
https://ad.lflucky.com/janes/img/s8.jpg
https://vi12x.xcle.cn/sucnew/640x150/20190909sg150.png
根据经验，除了js.hbssjd.cn域名外，其他均作了屏蔽处理

**Comment by metaphilium** [comment]
请求添加 m.vipijhhh13hfdbg.press，刚刚又被劫持到这个域名下了…
