### ISSUE TITLE
腾讯数据智库

### ISSUE THREAD

**Issue by sr093906** [vokins/yhosts#196]
https://tdc.qq.com/

核心优势

整合腾讯广告数据营销能力，实现全链路数据资产管理，完成标签、洞察、投放结构的统一化

便捷操作

赋能品牌自主操作，自由上传人群、查看标签，回顾投放，指导媒介营销策略，所见即所得

等等

**Comment by vokins** [comment]
已把这个域名加入，但是不知道有没有用，谢谢反馈。
