### ISSUE TITLE
关于手机网页版百度贴吧

### ISSUE THREAD

**Issue by yoyodadada** [vokins/yhosts#2]
能否去除手机网页版百度贴吧内的推广以及底部app推广链接？

**Comment by vokins** [comment]
http://tb1.bdstatic.com/tb/cms/ngmis/adsense/file_1454764255628.gif

比如这个可以用urlfilter拦截*/adsense/*但是不能拦截tb1.bdstatic.com主域名,因为主域名放了css文件,屏蔽了页面显示也不正常.
