### ISSUE TITLE
反馈一个彩云小译的误杀

### ISSUE THREAD

**Issue by Chandler-Lu** [vokins/yhosts#200]
屏蔽`ad.caiyunapp.com`后，彩云小译在登陆个人账号后会出现以下错误提示，并且会影响PDF文件上传后的预览。
虽然好像并不影响正常使用，但是屏蔽这个域名好像也确实没有减少什么广告。所以还是建议删除～谢谢～
![1](https://user-images.githubusercontent.com/18322610/70374483-a4f58d00-192d-11ea-8dac-c2e46ef20dd5.png)

**Comment by vokins** [comment]
感谢反馈，已经修复。
