### ISSUE TITLE
[感谢]我引用了贵项目，向你们表示感谢

### ISSUE THREAD

**Issue by gentlyxu** [vokins/yhosts#201]
我的项目是屏蔽广告的，将hosts转换成了dnsmasq和AdguardHome可以使用的过滤规则，项目地址是https://github.com/privacy-protection-tools/anti-AD    ，     主要是业余时间做了自己用的。引用了你们的列表之后，过滤效果有很好的改善，向你们表示感谢。

不知道该如何向你们申请授权，先写这里了。当然如果你们给予同意授权，那就更好了

**Comment by vokins** [comment]
可以。有数据问题优先反馈给我们，谢谢

**Comment by gentlyxu** [comment]
OK
