### ISSUE TITLE
荔枝FM

### ISSUE THREAD

**Issue by sr093906** [vokins/yhosts#208]
查看DNS日志，封禁后未受影响(普通听众)，供参考。  

collect.lzmoyin.com
proxy.lizhifm.com
proxy.lizhi.fm
stat.lizhifm.com
stat.lizhi.fm
netopt.lizhi.fm
crashin.lizhi.fm
apprds.lizhifm.com
rdstat.lizhifm.com
myip.lizhifm.com
lzgw.lizhifm.com

**Comment by vokins** [comment]
暂不接受，无源或无法验证数据提交，谢谢反馈
