### ISSUE TITLE
e小说网站打不开

### ISSUE THREAD

**Issue by weargle** [vokins/yhosts#212]
e小说网站地址是www.zwda.com，很好奇为什么屏蔽掉，是误杀吗

**Comment by vokins** [comment]
抱歉，可能在阿起开发的app自动获取数据的同时，造成误杀，又未进行对数据逐条人工审核造成。现已修复并加入白名单，感谢您的反馈。如果以后还有其他误杀，请及时反馈给我们，谢谢！

**Comment by vokins** [comment]
可能是由于在使用由阿起开发的app自动分析获取广告数据的同时造成误杀。而我在进行数据合并提交时又未逐条进行人工审核。
阿起开发的自动化工具已经长期运行将近两年了，大大节省了我们的人工查找广告的时间，提升了效率。感谢阿起！
现已修复并将此域名加入白名单，感谢您的反馈。如果以后还有其他误杀，请及时反馈给我们，谢谢！
