### ISSUE TITLE
误杀

### ISSUE THREAD

**Issue by operammm** [vokins/yhosts#22]
127.0.0.1 images.17173.com 这条误杀太严重了
http://news.17173.com/content/2016-08-07/20160807080126801_1.shtml 图片全给XX了
http://dq.sdo.com/  无法正常加载 不知道是哪条

@vokins

**Comment by operammm** [comment]
127.0.0.1 analytics.wanmei.com 导致http://manhua.dmzj.com/无法正常加载

**Comment by vokins** [comment]
以修复，请测试。
