### ISSUE TITLE
有道翻译不能正常使用

### ISSUE THREAD

**Issue by laggardkernel** [vokins/yhosts#25]
使用yhost后网页版有道无法正常翻译，无翻译结果显示；
yhosts version=201608272336
问题页面 http://fanyi.youdao.com/
经查实是由于impservice-test.dictapp.youdao.com被屏蔽导致，建议取消对有道翻译相关条目的屏蔽。

**Comment by kwoktree** [comment]
已修复,但是问题与明不是你说的这个,impservice都是广告与明,影响翻译功能的是 rlogs.youdao.com

**Comment by laggardkernel** [comment]
嗯，感谢。我也发现搞错了，的确是rlogs.youdao.com，刚想上来反馈来着。

**Comment by vokins** [comment]
@laggardkernel 感谢反馈~
