### ISSUE TITLE
写反了

### ISSUE THREAD

**Issue by coderstory** [vokins/yhosts#26]
cdnimage.shuaigay.xyz 198.41.206.62
cdnimage.shuaigay.xyz 198.41.206.63
cdnimage.shuaigay.xyz 198.41.206.64
cdnimage.shuaigay.xyz 198.41.206.65

这些是谁加上去的  真是个天才

**Comment by vokins** [comment]
来源是：http://www.shuaigay.top/thread-1066406-1-1.html
