### ISSUE TITLE
小白请问在openwrt下载的格式如何转换？

### ISSUE THREAD

**Issue by zasl** [vokins/yhosts#28]
能否把下载的内容格式转换为这种的
address=/google-analytics.com/127.0.0.1
小白不知道脚本命令的具体内容。谢谢

**Comment by vokins** [comment]
可以直接替换hosts,你现在说的这个是dnsmasq,你可以搜索相关教程.

**Comment by zasl** [comment]
因为hosts在路由器上性能比较差，所以想在dnsmasq上面部署，搜索了半天找不到教程。。。

**Comment by vokins** [comment]
https://www.freehao123.com/dnsmasq/

**Comment by vokins** [comment]
@zasl https://www.freehao123.com/dnsmasq/

**Comment by rampageX** [comment]
用：

    addn-hosts=/etc/yhosts

dnsmasq 可以动态读取 yhosts 文件，也就是 yhosts 更新了他会自动读取新的文件内容，无需重启 dnsmasq 本身。

**Comment by zasl** [comment]
现在就是想自动让他定时下载并且转换格式，因为hosts还是卡，如果实在不行只能hosts，有什么自动的脚本吗？

**Comment by tcneko** [comment]
```
#!/bin/bash
set -e
work_dir=`mktemp -d`
conf_file_name="adhost.conf"
wget -qO "${work_dir}/adhost.orl" https://raw.githubusercontent.com/vokins/yhosts/master/hosts
grep -E "^127.0.0.1 " ${work_dir}/adhost.orl > ${work_dir}/adhost.tmp
sed -ie 's!127.0.0.1 !address=/!;s!$!/127.0.0.1!' ${work_dir}/adhost.tmp
rm -f /etc/dnsmasq.d/${conf_file_name}
cp ${work_dir}/adhost.tmp /etc/dnsmasq.d/${conf_file_name}
rm -rf $work_dir
```

这样加个cron任务，周期性执行并重启dnsmasq，大概会有用的样子？

**Comment by KevinSJ** [comment]
可以安装openwrt的adblock包然后在/etc/config/adblock 文件中添加
```
config source 'yhosts'                   
        option adb_src 'https://raw.githubusercontent.com/vokins/yhosts/master/hosts'
        option adb_src_rset '\$0 ~/^127\.0\.0\.1[ \t]+([A-Za-z0-9_-]+\.){1,}[A-Za-z]+/{print tolower(\$2)}'
        option adb_src_desc 'Github Adblock yhosts list'
        option enabled '1'
```

**Comment by vokins** [comment]
https://github.com/sy618/hosts/blob/master/%E8%B7%AF%E7%94%B1%E5%99%A8%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0hosts/%E8%B7%AF%E7%94%B1%E5%99%A8%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0hosts%E6%95%99%E7%A8%8B.txt

**Comment by vokins** [comment]
长时间未回复，有问题请另开
