### ISSUE TITLE
staticxx.facebook.com問題

### ISSUE THREAD

**Issue by klib9739** [vokins/yhosts#32]
staticxx.facebook.com會導致Facebook應用程式或遊戲
無法發布貼文以及傳送邀請
請問遮蔽此網址原因為??

**Comment by vokins** [comment]
广告。请给出你说的问题的具体操作步骤以及截图，谢谢！

**Comment by klib9739** [comment]
使用Facebook玩https://apps.facebook.com/happyfishbowl/
遊戲內動態皆無法發布 無法送禮


sdk.js?v=1:81 GET https://staticxx.facebook.com/connect/xd_arbiter/r/LJ9CfGDsgQ7.js?version=42 net::ERR_NAME_NOT_RESOLVEDl @ sdk.js?v=1:81whenReady @ sdk.js?v=1:84init @ sdk.js?v=1:75create @ sdk.js?v=1:75ta @ sdk.js?v=1:84(anonymous function) @ sdk.js?v=1:84(anonymous function) @ sdk.js?v=1:77ba @ sdk.js?v=1:32fire @ sdk.js?v=1:77v @ sdk.js?v=1:127(anonymous function) @ sdk.js?v=1:91(anonymous function) @ sdk.js?v=1:89window.fbAsyncInit @ sns_2_2.js?v=3.71:39v.__wrapper @ sdk.js?v=1:89(anonymous function) @ sdk.js?v=1:127
sdk.js?v=1:55 GET https://staticxx.facebook.com/connect/xd_arbiter/r/LJ9CfGDsgQ7.js?version=42 net::ERR_NAME_NOT_RESOLVEDappend @ sdk.js?v=1:55appendHidden @ sdk.js?v=1:55(anonymous function) @ sdk.js?v=1:91k @ sdk.js?v=1:54
sdk.js?v=1:89 Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by klib9739** [comment]
看到修復了
感謝vokins的維護
