### ISSUE TITLE
提交百度云移动版页面的广告

### ISSUE THREAD

**Issue by neoFelhz** [vokins/yhosts#33]
gss2.bdstatic.com。
（由 via浏览器 网络日志功能抓取）

**Comment by neoFelhz** [comment]
还有这个
gsp0.baidu.com

**Comment by vokins** [comment]
谢谢反馈，为了防止误杀，暂时不接受您直接提交域名。
请您提交详细的页面URL地址以及重现方式，包括使用何种设备在移动还是wifi网络下访问。如果是网络日志请提交详细网络日志，谢谢！

**Comment by neoFelhz** [comment]
- 页面：移动版百度云网页的任何页面——包括分享页面和我的网盘页面
- 广告类型：banner

> 显示的是百度理财的广告。

- 浏览器：Andorid，via浏览器
- AD URL抓取方式：via浏览器网页日志功能

**Comment by neoFelhz** [comment]
日志：
![](https://img.imjad.cn/images/2016/11/09/Screenshot_20161109-181746.png)
还发现了 issuecdn.baidu.com 域名，直接链向了百度理财 banner 的 jpg。

**Comment by vokins** [comment]
issuecdn.baidu.com 域名之前加入过，后来去掉了，原因是有网友反馈此域名影响百度云app的视频插件的加载。gss2.bdstatic.com。gsp0.baidu.com这两个域名请告知具体页面，谢谢。

**Comment by vokins** [comment]
安卓版百度云app启动广告：
issuecdn.baidupcs.com/issue/netdisk/guanggao/cj720-1062-0203.jpg?network_type=wifi&vip=0
issuecdn.baidupcs.com/issue/netdisk/guanggao/xditu720-1062-0201.jpg?network_type=wifi&vip=0
但是此域名会影响解码器和搜索下载
issuecdn.baidupcs.com/issue/netdisk/videosdk/baidu_product_1_7_5_1/cyberplayer-core-armv7-neon-1.7.zip
可以下载解码器后屏蔽此域名。
127.0.0.1 issuecdn.baidupcs.com
或者屏蔽：
*/guanggao/*
