### ISSUE TITLE
为什么最近的更新里加入了奇怪的重定向

### ISSUE THREAD

**Issue by n2day** [vokins/yhosts#38]
uvwxyz.xyz，为什么会有这个网站的重定向，我不歧视，但不代表所有人都可以接受，搞不懂。

**Comment by vokins** [comment]
官方提供就会加入。看分类就清楚了。如果你有成人网站被屏蔽，你提供了官方的IP我们也可以加入。

**Comment by chutsetien** [comment]
建议你们和 racaljk 他们沟通一下，你们专注于做境内网站的广告屏蔽、恶意网站屏蔽等的，而把这些本地解析合并到 racaljk 那边去。不然你们的和 racaljk 有部分重叠每次跟新都还得再排查。
以及建议排查所有的激活验证屏蔽并删除（比如 Adobe 家的），这对订阅用户来说反而造成了无法连接的障碍，而且加入这些行即潜在意味着你们在支持盗版软件——而这从道义上来说并不正确。
以及：贵处的屏蔽类行中有大概 400 来行跟 StevenBlack 和 joeylane 两家的重叠了。这个我也不知道该如何建议好，或许你们可以把他两家的合并进来做成一个全球范围内的广告屏蔽、恶意网站屏蔽。
最后感谢你们的工作。
