### ISSUE TITLE
Google adservice 误杀

### ISSUE THREAD

**Issue by coolrc136** [vokins/yhosts#40]
127.0.0.1 www.googleadservices.com
在Google搜索结果页面点击广告后会跳转到  www.googleadservices.com ，然后由 www.googleadservices.com跳转到搜索结果，block 掉这个域名后如 腾讯云 阿里云 等购买了 Google AdWords 的网站在搜索结果页就没办法点进去了

**Comment by vokins** [comment]
www.googleadservices.com/pagead/aclk?sa=L&ai=CQ8y4I6z4VLrQK8y7lALTh4DIBIGYk7AJ8ZuetvwB6aGP89kCEAEggo3vBWDJ3uiGyKOQGaABh

会有类似网址啊！
