### ISSUE TITLE
uc浏览器新闻误杀

### ISSUE THREAD

**Issue by cokll** [vokins/yhosts#42]
新闻全部没图标了,不知道是那个域名

**Comment by vokins** [comment]
群内投票结果，建议去掉所有浏览器资讯，可以自行添加相关域名到白名单

**Comment by vokins** [comment]
127.0.0.1 iflow.uczzd.cn
127.0.0.1 api.mp.uc.cn
127.0.0.1 iflow.uczzd.com.cn
可以把uc下的内容清理干净

**Comment by cokll** [comment]
好的
