### ISSUE TITLE
福利吧PC端网页广告上报

### ISSUE THREAD

**Issue by n2day** [vokins/yhosts#43]
网址：http://fuliba.net/
操作平台：Windows 7
运营商：中国电信
![qq 20170205193123](https://cloud.githubusercontent.com/assets/13824934/22625808/98ebd82c-ebd9-11e6-869b-a827dd3bf14d.jpg)

**Comment by vokins** [comment]
div[class="widget_new"],header[role="banner"]{display: none !important;}

这个图片用的是新浪的图床，无法通过hosts方式去除（屏蔽后影响较大）。用上面的css样式表过滤吧

**Comment by vokins** [comment]
类似的网站还有成人网站如果不喜欢此类图片还可以使用我们的vip数据，屏蔽相关img域名
https://raw.githubusercontent.com/vokins/yhosts/master/vip/img.txt
