### ISSUE TITLE
广告提交

### ISSUE THREAD

**Issue by abc45628** [vokins/yhosts#46]
有广告的网页http://codego.net/272510/
广告地址 s.iroby.com
 z22.jxydsb.com
 qjgcdn123.86666608.com
电信

**Comment by abc45628** [comment]
另外提交一个误杀
files.jb51.net
网址http://www.jb51.net/article/57889.htm
虽然杀了广告，但是正文的图片也看不到了

**Comment by vokins** [comment]
感谢，数据已合并。
