### ISSUE TITLE
爱奇艺 客户端无法下载了

### ISSUE THREAD

**Issue by CNMan** [vokins/yhosts#47]
http://app.iqiyi.com/mobile/player/

下载地址域名：ota.iqiyi.com

**Comment by easyinplay** [comment]
如果需要可以在注释掉相关条目，不过话说回来 现在不都通过商店更新吗

**Comment by CNMan** [comment]
@easyinplay 我的下游项目[unbound.conf](https://github.com/CNMan/unbound.conf)用了这个hosts，用户反馈回来，代为反馈到上游:)
