### ISSUE TITLE
yhosts中关于irs01的条目与扩张ADfree.Player.Online冲突

### ISSUE THREAD

**Issue by easyinplay** [vokins/yhosts#48]
yhosts和ADfree.Player.Online都是国内使用量很大的去广告方法或者工具。
yhosts中关于irs01的指向会造成使用ADfree.Player.Online后视频黑屏，是否注释掉

感谢你的辛勤工作

**Comment by kingsey** [comment]
饭友吗？  我今天刚评论给ADfree这个问题 _(:3J∠)_

**Comment by easyinplay** [comment]
是啊，之前遇到了 顺便来这边提一下

 

哈哈 看来我多次一举了 

 

发件人: kingsey [mailto:notifications@github.com] 
发送时间: 2017年2月15日 16:37
收件人: vokins/yhosts <yhosts@noreply.github.com>
抄送: easyinplay <easyinplay@gmail.com>; Author <author@noreply.github.com>
主题: Re: [vokins/yhosts] yhosts中关于irs01的条目与扩张ADfree.Player.Online冲突 (#48)

 

饭友吗？ 我今天刚评论给ADfree这个问题 (:3J∠)

**Comment by vokins** [comment]
扩展的原理是遇到这个域名跳过，我这里是屏蔽访问。
如果我取消这个域名的屏蔽，那么用hosts就会有广告了。
有没有两全其美的办法呢？

**Comment by kingsey** [comment]
什么原理不清楚，刚改到irs01不久，之前是另一个似乎失效了。
插件的发布和维护者@cqhtyi

**Comment by cqhtyi** [comment]
我这里使用到 irs01.com 实现跨域，如果hosts文件屏蔽了这个域名，确实会导致ADfree无法使用。
之所以使用irs01.com也是无奈之举，这家的服务器还是厉害，全国访问都很快。

**Comment by vokins** [comment]
可以暂时停用hosts，在win下使用扩展。或者自己加入白名单。

**Comment by vokins** [comment]
irs01.com.netirs09已去除
