### ISSUE TITLE
ads.csdn.net

### ISSUE THREAD

**Issue by abc45628** [vokins/yhosts#49]
ads.csdn.net屏蔽这个网址的话会导致http://download.csdn.net/download/xmt1139057136/7436463
样式问题https://pan.baidu.com/s/1mi4qhb6

**Comment by abc45628** [comment]
不屏蔽这个的话也 只是多了一个横线https://pan.baidu.com/s/1hsaCfcS

**Comment by vokins** [comment]
感觉影响不大，暂时不去除。
