### ISSUE TITLE
 优酷播放记录

### ISSUE THREAD

**Issue by 10089** [vokins/yhosts#51]
PC 登录youku网页版 没有播放记录
试着找了下  不能确定具体哪个域名影响记录  

另外   cmstool.youku.com  这个域名影响删除播放记录

**Comment by vokins** [comment]
cmstool.youku.com 确定是这个吗？

**Comment by 10089** [comment]
cmstool.youku.com  这个域名影响删除记录

播放记录受不能记录的域名  还没有找到具体哪一个

**Comment by vokins** [comment]
ok暂时删除了这个域名

**Comment by 10089** [comment]
建议删除几个域名  
static.anquan.org  影响网站 https://www.anquan.org/seccenter/search/static.anquan.org
c.wrating.com     影响网站  土豆任何人的主页不能正常显示 如 http://v.tudou.com/DSnvlaoshi/?wc=0
mipcache.bdstatic.com  影响  手机版百度首页 当中的视频正常播放


另外需要添加的域名 
btrace.qq.com 
btrace.video.qq.com  
 腾讯的行为分析追踪  功能类似 cnzz

播放记录我有空找下具体哪个域名

**Comment by 10089** [comment]
https://github.com/vokins/yhosts/blob/387d3c758e1cfee09258cb5d6343fb3db496acf6/hosts#L969

**Comment by vokins** [comment]
static.anquan.org 很多网站插入了这个js，所以我这里不解除屏蔽。

**Comment by vokins** [comment]
mipcache.bdstatic.com 影响 手机版百度首页 当中的视频正常播放 我这边测试了几个播放都正常啊能否提供具体网址测试？

**Comment by vokins** [comment]
c.wrating.com 影响网站 土豆任何人的主页不能正常显示 如 http://v.tudou.com/DSnvlaoshi/?wc=0

另外需要添加的域名
btrace.qq.com
btrace.video.qq.com
腾讯的行为分析追踪 功能类似 cnzz


已修复，已加入，感谢反馈

**Comment by 10089** [comment]
请求添加几个手机后门  参考[链接1](http://www.solidot.org/story?sid=50401r)   [链接2](http://www.solidot.org/story?sid=50382)

127.0.0.1 adfuture.cn
127.0.0.1 bigdata.adfuture.cn
127.0.0.1 folder.adfuture.cn
127.0.0.1 fotacontrol.adfuture.cn
127.0.0.1 cm.adkmob.com
127.0.0.1 ssdk.adkmob.com
127.0.0.1 adsunflower.com
127.0.0.1 ebootv5.adsunflower.com
127.0.0.1 bigdata.adsunflower.com
127.0.0.1 folder.adsunflower.com
127.0.0.1 bigdata.advmob.cn
127.0.0.1 folder.advmob.cn
127.0.0.1 bigdata.adups.comj


还有这个 巨硬乐色站  被误屏蔽  www.msn.com

建议127.0.0.1  换为 0.0.0.0  如果本地建立测试网站、数据库的话 拖慢速度

**Comment by vokins** [comment]
www.msn.com 已去除
 我看了一下你说的这个部分内容我的数据里只有这两条没有包含，
127.0.0.1 ebootv5.adsunflower.com
127.0.0.1 bigdata.adups.com
已加入。

127.0.0.1 很通用不管是mac还是ios或者安卓，0.0.0.0
安卓要手动设置才有效，只有windows不需要设置可以识别。所以第三天建议不考虑。可以用本地的批处理批量替换即可，比如sed等

2017年3月12日星期日，10089 <notifications@github.com> 写道：

**Comment by 10089** [comment]
优酷记录观看视频时间较长才有记录可以 close  了
