### ISSUE TITLE
腾讯视频tv版（云视听极光）播放视频前出现广告

### ISSUE THREAD

**Issue by 25minutes** [vokins/yhosts#56]
已经正确应用了最新版hosts文件（包含hosts.txt 和tvbox.txt，#version=201703081135 ），在小米盒子上安装云视听极光版本2.3.1.1011（就是tv版的腾讯视频），播放视频（比如三生三世十里桃花）前还是出现（通常是60秒）广告视频，基本上播放各种电视剧/电影/综艺时都出现，请问有办法去除吗？
btw，云视听极光之前几个版本也有同样广告，尝试通过dnsmasq屏蔽了整个qq.com域名，也仍然无法屏蔽上述广告视频

**Comment by vokins** [comment]
tv版hosts方式过滤不完全，使用带有过滤功能的路由器吧

**Comment by 25minutes** [comment]
谢谢回复。技术上问一下，是不是因为腾讯视频tv版使用了特殊的方法从而不能用hosts屏蔽的方法去广告？我跟踪过它所有dns查询请求，也尝试屏蔽了一些可疑域名，似乎都不奏效

**Comment by vokins** [comment]
他的sd卡目录会缓存广告，以前我解包看过apk也会内置一些图片啥的广告，如果不是热门视频那么是没有广告的，但是一旦观看热门视频就会有广告了。以后再看非热门视频也有广告了。该加的hosts基本都加了。如果你用电视猫看腾讯的源就会发现没广告。魔力视频是用的优酷的广告，也无法再通过hosts方式去除了。域名是不奏效的。参见QQ浏览器就算使用了hosts依然无法屏蔽广告一样，腾讯所有数据可能也是为了自身安全考虑全部走自己的服务器直链。

2017年3月10日星期五，25minutes <notifications@github.com> 写道：

**Comment by 25minutes** [comment]
明白了，再次感谢！

**Comment by vokins** [comment]
不客气，如果路由器支持abp类过滤方式就更好了

2017年3月10日星期五，25minutes <notifications@github.com> 写道：

**Comment by 25minutes** [comment]
关于abp的过滤方式再请教一下，好像目前主流的方案是adm和abyby，以你的经验推荐哪种方案？过滤规则需要自己配置吗，如果需要的话网上有比较好的资源提供这些规则来屏蔽视频广告吗？谢谢

**Comment by sy618** [comment]
就目前来说，abp规则最成熟、更新最及时的就两家：
adbyby（老牌）
koolproxy（后起之秀）
这两种都可以部署到路由器上。

**Comment by 25minutes** [comment]
多谢，那么我就选adbyby吧，是不是只需要下面这个规则？
https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt

**Comment by 25minutes** [comment]
费了点周折，最后成功安装了arm版本的adbyby，规则就是上面的两条，目测效果相当完美
算是把淘汰下来的1分钱天猫魔盒1代废物利用了 :)
非常感谢版主的经验分享！
