### ISSUE TITLE
贴吧app内推广下载链接

### ISSUE THREAD

**Issue by giveup** [vokins/yhosts#58]
lnk0.com
详见：http://doc.talkingdata.com/posts/160
iOS 贴吧 App 不小心点击的话,会先经baidu.com跳转,接着跳转到lnk0.com,最后直接跳转到App Store.而且没有任何提示,比较恶心.
本来想发PR的,但是不知道放在哪里比较合适

**Comment by vokins** [comment]
加了一个#talkingdata.net
127.0.0.1 a.adnet.com
127.0.0.1 tdcv3.talkingdata.net
127.0.0.1 lnk0.com 的分类在广告联盟union.txt里面
请问如何才能在这些sdk里面快速的发现域名？有没有什么好的方法？
