### ISSUE TITLE
恩山无线论坛和驱动之家的广告不能去除

### ISSUE THREAD

**Issue by 1900forever** [vokins/yhosts#63]
请看：
http://www.right.com.cn/forum/forum.php
或任意一条驱动之家的新闻页面标题上方和页面左侧：
http://news.mydrivers.com/1/526/526959.htm
使用adbp则可以完全过滤

**Comment by vokins** [comment]
原理不同，hosts只能过滤域名，无法像adp那样做元素选择过滤。
