### ISSUE TITLE
QQ电脑管家个人中心任务列表出不来

### ISSUE THREAD

**Issue by kuaitou286** [vokins/yhosts#65]
登录QQ电脑管家
![tim 20170412090216](https://cloud.githubusercontent.com/assets/10684972/24936776/be981672-1f5e-11e7-81df-db1afcb92a62.png)

点击任务
![tim 20170412085934](https://cloud.githubusercontent.com/assets/10684972/24936748/7e50a0ac-1f5e-11e7-83e4-a1233b5de299.png)

**Comment by vokins** [comment]
自己组合不要添加数据，down.txt数据试试

**Comment by vokins** [comment]
自己组合数据吧。不要添加down.txt数据试试

**Comment by kuaitou286** [comment]
找到了，是 ` c.pc.qq.com ` 的问题  注释这条就可以了

**Comment by vokins** [comment]
ok 已经修复。
