### ISSUE TITLE
墓穴迷城 电影网1905出现底层广告

### ISSUE THREAD

**Issue by yoyodadada** [vokins/yhosts#7]
readme里测试链接墓穴迷城出现底层广告，手机端，UC浏览器，已关闭云加速，使用小马修改的UC经典版v88.8.8.888，网页链接：http://www.1905.com/vod/play/969015.shtml

**Comment by vokins** [comment]
未见明显广告，请告知网络环境，并判断是否有劫持？请确认hosts去广告文件是否只是单纯使用此数据，并确认是否生效？网页分析未见有异常。
<title>1905电影网广告</title>
<script src="http://afp.m1905.com/asp_js/k.js"></script>
</head>
_acK({ aid: aid, format: 0, mode: 1, gid: 1,async:0, serverbaseurl: "tga.csbew.com/"});
<script language="JavaScript" src="http://counter.m1905.com/count.php?contentid=969015"></script>
<script src=" http://hm.baidu.com/h.js?49411f7bde52035653f2e2b70a0bb6a5" type="text/javascript"></script>
此几处域名已屏蔽
如果需要请远程帮助，请联系。

**Comment by vokins** [comment]
算了，请先使用电脑浏览器查看hosts是否生效，并确认此网站在电脑上有无广告。如无，则可能是运营商劫持。请告知并联系我远程处理。

**Comment by yoyodadada** [comment]
没有了，可能是我的浏览器缓存广告，麻烦了，关闭此贴吧。

**Comment by vokins** [comment]
好的，不排除运营商劫持的可能，如果再次出现问题，请回复此帖。
