### ISSUE TITLE
求去BT之家顶部、左右两侧大面积横幅广告

### ISSUE THREAD

**Issue by n2day** [vokins/yhosts#73]
BT之家-BT电影天堂-影视资源交流社区
http://www.btbtt.co/
![snipaste_2017 04 26](https://cloud.githubusercontent.com/assets/13824934/25425204/c3620042-2a9d-11e7-8e90-df4e33a35079.png)

**Comment by sy618** [comment]
这个网站的广告单纯靠hosts是无法去掉的。

顶部广告是：
127.0.0.1 bbsimages.zkxf119.com
屏蔽后会有残留框。

但可以用abp规则来完美屏蔽：
加这两条就干净了
||www.btbtt.co/view/image/*.jpg
||www.btbtt.co/imgs.js*

**Comment by n2day** [comment]
谢谢楼上，问题解决，如果能用hosts过滤最好了，广告过滤扩展毕竟消耗资源。
