### ISSUE TITLE
前几天下软件中招了....

### ISSUE THREAD

**Issue by wszgrcy** [vokins/yhosts#75]
好久没中招了,就是那种下来后在后台偷偷的安装一些9流网页游戏的那种..........当时记得有个下载站,貌似是纯数字的,下的东西都是有后台偷偷安装的,不知道如何能获取到链接的网页(就是获取到这个偷偷下载垃圾游戏的网址,不是说找这个网站,是已找到情况下找他的下载部分.....希望我表达明白了),如果有方法的话我愿意做小白鼠再试一次

**Comment by sy618** [comment]
把那个原网址发出来看看。
或者你自己用抓包工具分析。

**Comment by wszgrcy** [comment]
@sy618 有工具能提供下吗

**Comment by vokins** [comment]
可以使用各种网络分析软件，比如说http://www.telerik.com/fiddler
最好能够提供一下网址我们看看。谢谢

**Comment by vokins** [comment]
长时间未回复，有问题请另开
