### ISSUE TITLE
优酷失效

### ISSUE THREAD

**Issue by yangchangyz** [vokins/yhosts#77]
新版优酷去广告失效很久了，使用旧版却一如既往的好效果。但就是打开

**Comment by yangchangyz** [comment]
新版优酷去广告失效很久了，使用旧版却一如既往的好效果。但就是打开弹出更新，点现在下载才能进入，请问应该添加哪条屏蔽呢？谢谢

**Comment by vokins** [comment]
用旧版就可以了，新版广告ip直连无法通过hosts屏蔽
