### ISSUE TITLE
Can't update miui rom

### ISSUE THREAD

**Issue by exodius48** [vokins/yhosts#8]
Hello,
I'm using this hosts to block ads on miui rom. But latest update break miui update, my device can't check update from miui server. I integrate this hosts into Unbelovedhosts xposed module.
Because of this 

`#miui-system-update
127.0.0.1 update.miui.com`

Please on next update remove that line. Thank you.

**Comment by vokins** [comment]
您好，抱歉我英语不够好。
说一下我屏蔽miui升级的原因。
我购买的是红米note2，在6.3.17这个开发版本中异常的耗电，因此我回退到6.3.10这个开发版中并暂时屏蔽了miui的升级域名服务。
在最新可以获取的miui6.3.24这个开发板已经解决了这个问题。
我已经在最新的数据里删除了这条信息。
问题已解决，请升级到最新版。感谢您的反馈。


The problem has been resolved, please upgrade to the latest version. Thank you for your feedback.

**Comment by exodius48** [comment]
Nice, thanks bro. Problem fixed.
