### ISSUE TITLE
为什么要屏蔽 Bmob

### ISSUE THREAD

**Issue by Trumeet** [vokins/yhosts#81]
我开发的一些App使用了Bmob的付款服务，很多用户修改了hosts之后就无法验证购买了。
这两天才发现是这里屏蔽掉了（
为什么要屏蔽呢？望解答/去掉，谢谢啦~

**Comment by vokins** [comment]
在记录里找到了，优酷调用bmob的广告的记录，暂时去掉了。

**Comment by Trumeet** [comment]
嗯好的，谢谢！ @vokins
