### ISSUE TITLE
请在使用我的项目代码的时候署名并且附上MIT协议文件

### ISSUE THREAD

**Issue by lennylxx** [vokins/yhosts#82]
你在本项目(yhosts)中添加了一份用于更新hosts的源代码，链接如下
https://github.com/vokins/yhosts/blob/368c455e0a817b49dfb002cf1b0ca96eca9d5394/mac/updatehosts.py
这份代码是原原本本从我的项目复制过来的，链接如下
https://github.com/lennylxx/ipv6-hosts/blob/master/update_hosts.py
两份文件文件名类似，并且内容包含所有的字节均一致。

虽然我的项目(ipv6-hosts)采用了比较宽松的MIT协议，但是并不代表着你可以直接引用而不署名和不附上相应的MIT协议文件。
协议文件链接：https://github.com/lennylxx/ipv6-hosts/blob/master/LICENSE

如果你不清楚MIT协议的约束，请阅读以下网页：
https://www.zhihu.com/question/25079718
https://zh.wikipedia.org/wiki/MIT%E8%A8%B1%E5%8F%AF%E8%AD%89

**Comment by lennylxx** [comment]
你在此项目(yhosts)的首页([README.md](https://github.com/vokins/yhosts/blob/master/README.md))中声明此项目采用署名-非商业性使用-禁止演绎 CC BY-NC-ND协议，但是要求别人之前能否请您自己先署名来源呢？
谢谢。

**Comment by vokins** [comment]
抱歉，已删除。

**Comment by lennylxx** [comment]
很高兴看到正面的反馈，谢谢。

**Comment by vokins** [comment]
之前使用了您的项目文件目的是删除和清理一些不存在的域名。非常抱歉。

**Comment by vokins** [comment]
我把这个放到wiki 里面这样写可以吗？
https://github.com/vokins/yhosts/wiki/软件运行库

**Comment by lennylxx** [comment]
可以的，你甚至可以在自己的项目添加子模块
https://git-scm.com/book/zh/v1/Git-%E5%B7%A5%E5%85%B7-%E5%AD%90%E6%A8%A1%E5%9D%97 
或者干脆复制过来。
但是需要署名来源，并且附上原始的copyright license。

**Comment by vokins** [comment]
子模块太复杂，感觉现在这样版权也不不是很明确，我要回头readme的事情详细修改一下，谢谢。
