### ISSUE TITLE
你好，能添加小米电视和电视盒子的屏蔽广告吗

### ISSUE THREAD

**Issue by cnrock** [vokins/yhosts#84]
你好，能添加小米电视和电视盒子的屏蔽广告吗,地址如下
127.0.0.1 stat.pandora.xiaomi.com
127.0.0.1 upgrade.mishop.pandora.xiaomi.com
127.0.0.1 logonext.tv.kuyun.com
127.0.0.1 config.kuyun.com
127.0.0.1 api.io.mi.com
127.0.0.1ishop.pandora.xiaomi.com
127.0.0.1 dvb.pandora.xiaomi.com
127.0.0.1 api.ad.xiaomi.com
127.0.0.1 de.pandora.xiaomi.com
127.0.0.1 data.mistat.xiaomi.com
127.0.0.1 jellyfish.pandora.xiaomi.com
127.0.0.1 gallery.pandora.xiaomi.com
127.0.0.1 o2o.api.xiaomi.com
127.0.0.1 bss.pandora.xiaomi.com
127.0.0.1 gvod.aiseejapp.atianqi.com
127.0.0.1 api.io.mi.com
127.0.0.1 ad.mi.com
127.0.0.1 ad.xiaomi.com
127.0.0.1 ad1.xiaomi.com

**Comment by vokins** [comment]
127.0.0.1 bss.pandora.xiaomi.com
127.0.0.1 de.pandora.xiaomi.com
127.0.0.1 dvb.pandora.xiaomi.com
127.0.0.1 jellyfish.pandora.xiaomi.com
127.0.0.1 stat.pandora.xiaomi.com

**Comment by vokins** [comment]
127.0.0.1 upgrade.mishop.pandora.xiaomi.com
127.0.0.1 gallery.pandora.xiaomi.com
127.0.0.1 o2o.api.xiaomi.com
127.0.0.1 api.io.mi.com
127.0.0.1 ishop.pandora.xiaomi.com
这部分从域名看都是重要的域名，跟广告好像也没有关系，都是升级，相册，商城，所以没有添加。

**Comment by vokins** [comment]
127.0.0.1 gvod.aiseejapp.atianqi.com
127.0.0.1 ad.mi.com
127.0.0.1 ad.xiaomi.com
127.0.0.1 ad1.xiaomi.com
这一部分没有确定，暂时未添加。

**Comment by vokins** [comment]
由于我暂时没有测试环境，无法确切的确认具体域名数据，如果方便可以加群讨论。

**Comment by lw960105** [comment]
能不能去小米電視強制升級系統？

**Comment by vokins** [comment]
@lw960105 我没有小米电视，你可以分析一下网址自己添加到自己路由器的dnsmasq，具体教程网上都有。

**Comment by vokins** [comment]
长时间未回复，暂时关闭，有问题请另开
