### ISSUE TITLE
关于Bmob SDK在后台加载广告，播放视频一事

### ISSUE THREAD

**Issue by ZeroAurora** [vokins/yhosts#85]
近期我在酷安上面发现一些应用开始在后台播放广告声音，例如Trumeet开发的Dir,天是一般蓝开发的搜图神器,foreverhgx开发的神奇磁力,s562218开发的MT管理器等等。
Trumeet的文章(不能找到别的开发者的文章莫喷):https://hexo.trumeet.top/2017/05/28/bmob-seo/
所以希望Host开发者能采取权衡“支付”与“广告”，采取折中措施，保证使用者免受广告侵扰。

**Comment by vokins** [comment]
重新加入bmob的屏蔽
