### ISSUE TITLE
淘宝pc端收藏宝贝 (XXX人气)不显示

### ISSUE THREAD

**Issue by BiuZero** [vokins/yhosts#86]
经过逐一排查，应该是`127.0.0.1 count.taobao.com` 导致的

**Comment by vokins** [comment]
最好能截图说明一下。我不是很清楚这个的具体意义。如果不方便在群里发图片即可。

**Comment by BiuZero** [comment]
![qq 20170530213520](https://cloud.githubusercontent.com/assets/15268027/26585842/f1b9ed86-457f-11e7-9151-54d1be9736d7.jpg)
![qq 20170530213359](https://cloud.githubusercontent.com/assets/15268027/26585841/f1b50938-457f-11e7-8f17-b5722798f0aa.png)
如图

**Comment by vokins** [comment]
非常感谢反馈，已修复。
