### ISSUE TITLE
广点通影响用户体验

### ISSUE THREAD

**Issue by ZeroAurora** [vokins/yhosts#88]
手机内置了广点通插件
常用软件启动时插播3秒广告
上网页底部出现广告

**Comment by ZeroAurora** [comment]
抓不到包，拦不住

**Comment by vokins** [comment]
apk是什么？这样说的太笼统，不清楚

**Comment by ZeroAurora** [comment]
自带的设备服务

**Comment by vokins** [comment]
什么设备什么型号你也没说，我的手机没这服务

**Comment by ZeroAurora** [comment]
非常抱歉，手机是Lenovo VIBE P1，系统是VIBE UI V3.1，Android 6.0.3。设备服务安装包提取出来了， http://pan.baidu.com/share/link?shareid=917074726&uk=2252123618 ，应该是推送过来，自动安装。最烦这样的强制广告了。

**Comment by vokins** [comment]
https://github.com/vokins/yhosts/blob/master/%23.txt
根据您提供apk文件反编译后打得到如下数据，悉数加入数据中，还烦请多帮忙测试，看是否有误杀？谢谢
更新hosts数据后，务必在系统中找到这个服务，清除数据再试

**Comment by ZeroAurora** [comment]
感谢维护者的回复，更新hosts文件后暂未发生误杀现象，原有广告已经消失。待到发现误杀后，另开Issue
再次感谢。
