### ISSUE TITLE
爱奇艺有没有办法去广告

### ISSUE THREAD

**Issue by ziking** [vokins/yhosts#9]
爱奇艺有没有办法去广告

**Comment by vokins** [comment]
爱奇艺有广告在windows平台？
如果是那么在win平台无法去除。
如果是ios和安卓平台使用hosts文件。
如果还不能解决，请提供联系方式，平台版本，软件版本。操作详细步骤。

**Comment by ziking** [comment]
IOS最新版本7.4
屏蔽IP101.227.14.82
/81/ 
是可以的。
不知道HOSTS怎么搞。

**Comment by ziking** [comment]
屏蔽这个IP 101.227.14.84广告也不会出现

**Comment by vokins** [comment]
我这里无法重现你的问题，请确定是否是运营商劫持。

**Comment by vokins** [comment]
长时间未回复，有问题请另开
