### ISSUE TITLE
安卓未root能用ios的ad.js吗？

### ISSUE THREAD

**Issue by qw4096** [vokins/yhosts#92]
现在我的手机root需求就只剩下广告过滤这一个了，不想单单因为这个需求root，能不能用ios的ad.js这个方法？如果不行，能做个类似的吗？或者有什么别的方法吗，不用root

**Comment by vokins** [comment]
1.ad.js不是我的原创，我只是fork以后自己修改了规则。因为老婆喜欢用iPad看视频，所以以前在更新，但是现在我的iPad已经卖了。而且我和老婆在“爱奇艺”，“腾讯视频”，“优酷”，“芒果TV”，“迅雷看看”等都有充值的会员，所以我fork的那个ad.js项目我已不再维护。
2.安卓手机未root的完全没必要用ad.js，哪个是为ios设备设计，不能保证所有的安卓设备都兼容。
但是我们有未root手机更好的解决方案。[iTXTech Daedalus](https://github.com/iTXTech/Daedalus)
下载使用这个app根据需要选择对应的去广告，fq方案即可。

**Comment by qw4096** [comment]
多谢，我这就去试试。回复这么快真是excited
