### ISSUE TITLE
wap3.ucweb.com

### ISSUE THREAD

**Issue by bdfish** [vokins/yhosts#94]
Download Quark browser from `myquark.cn` need this.

**Comment by vokins** [comment]
没看懂

**Comment by vokins** [comment]
http://wap3.ucweb.com/files/components/ppappstore/3/ppappstore_V2.1.0.1_6_Build201702221447.apk?auth_key=1496026135-0-0-0bd13f65455181b42e5d01603bdafbc1&SESSID=7cdf3113e8c43de7737eb32f14c99e42
这个域名会从后台下载ppstore，所以屏蔽了。暂不解除。
