### ISSUE TITLE
淘宝无法跳转

### ISSUE THREAD

**Issue by Loukky** [vokins/yhosts#95]
淘宝搜索的商品无法跳转，屏蔽该行就解决了
127.0.0.1 click.simba.taobao.com

**Comment by vokins** [comment]
在哪个网站搜索出现问题，请提供具体网址和搜索关键词！

**Comment by Loukky** [comment]
就是淘宝搜索的商品，任意搜索的，

**Comment by vokins** [comment]
比如在淘宝网站https://www.taobao.com/
搜索小米6，得到的网址如下：
https://s.taobao.com/search?q=%E5%B0%8F%E7%B1%B36&imgfile=&ie=utf8&app=detailproduct&through=1
下面的宝贝链接都可以访问，页面右侧的掌柜热卖旁边明显标注了广告！
其广告链接为：https://click.simba.taobao.com/cc_im?spm=a230r.1.0.0.AAbwjZ&p=%D0%A1%C3%D76&s=1335134433&k=493&e=jZylxozOMJ4ZJRTsgDII4NFE9%2FRb8s9aEkwrPIIm8zC7UrxwMGrhp0xOV7g0ZjATKg4N%2B1kSxAUY65fgpAmaFEX75ip%2FRu3wYgHPP8k3Y8BTu00GuTFWQ02Tgq5W3WjC0RPXGaYTkLEyv9eXx77tm6K%2BwJAK6uByxHWff6ug0CTV%2FJKFHYsRVOLQ9arpW%2FZUlesE4uUwn2KFlvmnQas%2BPspUdXQRT0A%2F30mFws8GxcvaTqqXWZx5RFuy%2FffKKYO2V4EKGJH04TXKBQZ%2BlnSHqovOz0Fm5rgUXxJoi249xdGzffoKJ3Z9%2FaAEEa0vCs05Fcnyss9qkFCfCPanncF0WywqVDrl7GsYXYLLuHJdNZIpoB0fl9YNRQsp0lDQjsuDe2WSdN1PeZSAHTE6ozUt8vUcLa7B8SfEyG5MZr1cbAOlMPjRabN1BRE11%2FrIxeYOqNQuwqh0%2Fr5Hq4KiRyaiQ5ksDG%2BCC%2BbMqg6kxsF5cs4%3D

**Comment by Loukky** [comment]
搜索出来以后，点进去天猫店，会先跳转
https://click.simba.taobao.com/cc_im?spm=a230r.1.14.1.vXKkwZ&p=%C8%E2%CB%BF&s=8685314&k=577&e=YNz3Ze8EDWjbcwZGBVrmFS%2BvxgWO7%2BVUPqyf69XXsG0LjbztdyAEf2NtFav2hi9HEWerQ0Ye7SpF%2FQOrthdpciaps20J1l8qk4O0G7dOzZpAIElnb%2BaJKDMtJjj%2FQgLaIoGsiaPrAhJGYLz9lYiNntvSPJbb5ZTm9osPGg76NeEHDpFvcMbKL25Z2xtSM0u1a%2Bq0kWbiM21YC5bA8v6DEzZ5Iv2BgKFegmsgM2we1pyK16PcZHgdV1NdgPwNLK2fRmSfvoMmq68Kw9wB9G%2Fz4tNMIdJXyNJh%2FQzAz6dLqCO07pX1bFUnw0Jj%2F3tTHBxrdbDVPulVlg5CuGVX%2B%2Bt%2BZG5jA2aoKI5I4%2BmXWkkUo5jKiopWmWDZL3yyINxaZ6pgg3AdcuIe3iKz082eCoBR0w%2BokFwubuiyhLlM%2BdiD5WJ%2FJpqOSzdLGg4VXHdk4ifz3tCtyC9Y2dxKuZ3iyQLWLBAiQ1SHFSFukCRTaOZ9Rxyg1gO6WNj3VwdBtl4LpRAv7IqkJ1UVojT52f8Yv0zNe9bmlPwqf7LUuhdc3Yx7Uf0DNlvCedWUrV00xHL18bze
而这个恰好被屏蔽所以跳转不了

**Comment by vokins** [comment]
请提供具体的搜索关键词。

**Comment by Loukky** [comment]
实际上就是你说的那种链接，因为有些商品会从这种链接跳转，也就是前面是HTTPS://click.simba.taobao.com 后面一大堆参数的这种

**Comment by vokins** [comment]
你不提供关键词我就无法具体重现分析页面，我上面举得例子，淘宝上明确标注了这是广告。

**Comment by Loukky** [comment]
我随便搜索的关键字：肉丝，得到链接 https://s.taobao.com/search?q=%E8%82%89%E4%B8%9D&imgfile=&commend=all&ssid=s5-e&search_type=item&sourceId=tb.index&spm=a21bo.50862.201856-taobao-item.1&ie=utf8&initiative_id=tbindexz_20170618
然后下面提示：您好 ***，“肉丝” 相关的宝贝：黄钻爱买店铺 找到 4 件回头客爱买店铺 找到 4 件
选择第一个“ 浪莎丝袜防勾丝连裤袜春秋款中厚美腿打底袜薄款肉色瘦腿袜子女”。这个链接就是以https://click.simba.taobao.com/cc_im?spm=a230r.1.14.1.h5ehBT&p=%C8%E2%CB%BF&s=1379601383&k=569&e=5Imtmi7brr0javXqL7ySbrMEBVOXmZr33cSFcVEXqKPgEYBPI6RSbSIVHOmYvw%2BE1qY883PIaPuQJ1U7GVkaFnUHxVEFyeV87cZfkepSxzGAm823WnzCMu0PhxRq3P8%2BwlvFQLQunPYTbK3GHA1x0JYOak55dWNV52wDSQFsIHgHGjvqz09%2F%2FSCJwsEtxizVXYEzOOxDtzP79gvNuwKYvybLxrbAsVjLzi19Mk3Ib2a6%2FLSdS0u0rsDCwc6J3APri7Qyna%2B8W7TMH%2F8QD2PYt7RJSzCdM7thPCmwUwdOZtb2lMrXJ3TEQUtnFvqhzsA6wTMxZrqw5yKRAlsjRLwdTRy9mN6S4OZ5Jyy6NhDzCGJOShFpndCi%2BJNRi%2FC%2Fr6gRj64x%2FcGsHXPS8WjMP6kFkqhuhh7GUKlnIFJWWUs0btM9W4Q%2FI7DDreFOV1%2Ba6mdppgU8j4EOBlXj1K4sxK8N%2FxnE4nNHHrkPg7F8g4EA%2Fqd171h3z0CRglBYzpIw%2BP6TYQo3uPM8tR8pyCw4SxI50KAUhtgNp758MGvsjm2SY2fGK8TZpejPmw%3D%3D
这种情况存在的。

**Comment by vokins** [comment]
你看你提供的这个关键字，这个浪莎丝袜右下角有“广告”两个字

**Comment by Loukky** [comment]
看到了，是有广告两个字。。。不过这种广告我觉得不应该被拦截。。。

**Comment by vokins** [comment]
淘宝官方都写了是广告，你不想拦截自己加白名单即可。
