### ISSUE TITLE
jd活动页无法跳转

### ISSUE THREAD

**Issue by qingxiwa** [vokins/yhosts#96]
无法访问此网站
c-nfa.jd.com 拒绝了我们的连接请求。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
**ERR_CONNECTION_REFUSED_
不知道为何上传照片总是失败，通过赛风翻墙也不行，把图片上传到度盘，不介意看一下吧
其实就是jd主页jd.com
body > div.fs > div.grid_c1.fs_inner > div.fs_col2 > div > div.J_slider_main.slider_main

**Comment by vokins** [comment]
其提供跳转前的页面链接。否则我们可以合理的认为这类域名属于cps跳转返利链接。/adclick?
