### ISSUE TITLE
od.qingting.fm是播放有声小说的地址，不能屏蔽

### ISSUE THREAD

**Issue by hzcxdgioa** [vokins/yhosts#97]
od.qingting.fm屏蔽了之后，就没法听有声小说了，这是一个错误的屏蔽地址

**Comment by vokins** [comment]
进入主页后，小说类目下的鬼吹灯和畅销小说类目下的兵王混都市都是可以播放的，请提供无法播放的具体链接，或者重现的具体方法，比如搜索什么无法播放

**Comment by hzcxdgioa** [comment]
重现地址：http://www.qingting.fm/channels/210603
最近几天发现不能播放，才想到可能是因为广告屏蔽的关于，在控制台中发现了媒体文件链接不通，也在hosts中确实发现了相关域名，
http://od.qingting.fm/m4a/58d09ae77cb89172647fbb31_6974799_64.m4a
删除后就正常了

**Comment by vokins** [comment]
收到，感谢反馈。
